### ISSUE TITLE
Wrong duration "by task" in Statistics

### ISSUE THREAD

**Issue by tk0e** [adfinis/timed#73] opened 2023-11-01 08:19 UTC
Hi 

Since a while when filtering for
- Customer
- Project
- Time range from
- Time range to

in the "by Task" tab of the statistics module, the calculation is wrong. It seems as if the "Time range from" value is ignored.

If only "Time range from" is set, but not "Time range to", then the calculation is correct.

I'd appreciate a quick fix or a proposal for a workaround.

Cheers, Thomas

**Comment by c0rydoras** [comment] 2024-08-13 12:14
duplicate of #89

**Closed by c0rydoras** 2024-08-13 12:14 UTC
Labels: bug
